// This file is generated by rust-protobuf 2.7.0. Do not edit
// @generated

// https://github.com/Manishearth/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `mirbft.proto`

use protobuf::Message as Message_imported_for_functions;
use protobuf::ProtobufEnum as ProtobufEnum_imported_for_functions;

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_7_0;

#[derive(PartialEq,Clone,Default)]
pub struct Msg {
    // message oneof groups
    pub field_type: ::std::option::Option<Msg_oneof_type>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a Msg {
    fn default() -> &'a Msg {
        <Msg as ::protobuf::Message>::default_instance()
    }
}

#[derive(Clone,PartialEq,Debug)]
pub enum Msg_oneof_type {
    preprepare(Preprepare),
    prepare(Prepare),
    commit(Commit),
    forward(Forward),
    checkpoint(Checkpoint),
}

impl Msg {
    pub fn new() -> Msg {
        ::std::default::Default::default()
    }

    // .mirbft.Preprepare preprepare = 1;


    pub fn get_preprepare(&self) -> &Preprepare {
        match self.field_type {
            ::std::option::Option::Some(Msg_oneof_type::preprepare(ref v)) => v,
            _ => Preprepare::default_instance(),
        }
    }
    pub fn clear_preprepare(&mut self) {
        self.field_type = ::std::option::Option::None;
    }

    pub fn has_preprepare(&self) -> bool {
        match self.field_type {
            ::std::option::Option::Some(Msg_oneof_type::preprepare(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_preprepare(&mut self, v: Preprepare) {
        self.field_type = ::std::option::Option::Some(Msg_oneof_type::preprepare(v))
    }

    // Mutable pointer to the field.
    pub fn mut_preprepare(&mut self) -> &mut Preprepare {
        if let ::std::option::Option::Some(Msg_oneof_type::preprepare(_)) = self.field_type {
        } else {
            self.field_type = ::std::option::Option::Some(Msg_oneof_type::preprepare(Preprepare::new()));
        }
        match self.field_type {
            ::std::option::Option::Some(Msg_oneof_type::preprepare(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_preprepare(&mut self) -> Preprepare {
        if self.has_preprepare() {
            match self.field_type.take() {
                ::std::option::Option::Some(Msg_oneof_type::preprepare(v)) => v,
                _ => panic!(),
            }
        } else {
            Preprepare::new()
        }
    }

    // .mirbft.Prepare prepare = 2;


    pub fn get_prepare(&self) -> &Prepare {
        match self.field_type {
            ::std::option::Option::Some(Msg_oneof_type::prepare(ref v)) => v,
            _ => Prepare::default_instance(),
        }
    }
    pub fn clear_prepare(&mut self) {
        self.field_type = ::std::option::Option::None;
    }

    pub fn has_prepare(&self) -> bool {
        match self.field_type {
            ::std::option::Option::Some(Msg_oneof_type::prepare(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_prepare(&mut self, v: Prepare) {
        self.field_type = ::std::option::Option::Some(Msg_oneof_type::prepare(v))
    }

    // Mutable pointer to the field.
    pub fn mut_prepare(&mut self) -> &mut Prepare {
        if let ::std::option::Option::Some(Msg_oneof_type::prepare(_)) = self.field_type {
        } else {
            self.field_type = ::std::option::Option::Some(Msg_oneof_type::prepare(Prepare::new()));
        }
        match self.field_type {
            ::std::option::Option::Some(Msg_oneof_type::prepare(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_prepare(&mut self) -> Prepare {
        if self.has_prepare() {
            match self.field_type.take() {
                ::std::option::Option::Some(Msg_oneof_type::prepare(v)) => v,
                _ => panic!(),
            }
        } else {
            Prepare::new()
        }
    }

    // .mirbft.Commit commit = 3;


    pub fn get_commit(&self) -> &Commit {
        match self.field_type {
            ::std::option::Option::Some(Msg_oneof_type::commit(ref v)) => v,
            _ => Commit::default_instance(),
        }
    }
    pub fn clear_commit(&mut self) {
        self.field_type = ::std::option::Option::None;
    }

    pub fn has_commit(&self) -> bool {
        match self.field_type {
            ::std::option::Option::Some(Msg_oneof_type::commit(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_commit(&mut self, v: Commit) {
        self.field_type = ::std::option::Option::Some(Msg_oneof_type::commit(v))
    }

    // Mutable pointer to the field.
    pub fn mut_commit(&mut self) -> &mut Commit {
        if let ::std::option::Option::Some(Msg_oneof_type::commit(_)) = self.field_type {
        } else {
            self.field_type = ::std::option::Option::Some(Msg_oneof_type::commit(Commit::new()));
        }
        match self.field_type {
            ::std::option::Option::Some(Msg_oneof_type::commit(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_commit(&mut self) -> Commit {
        if self.has_commit() {
            match self.field_type.take() {
                ::std::option::Option::Some(Msg_oneof_type::commit(v)) => v,
                _ => panic!(),
            }
        } else {
            Commit::new()
        }
    }

    // .mirbft.Forward forward = 4;


    pub fn get_forward(&self) -> &Forward {
        match self.field_type {
            ::std::option::Option::Some(Msg_oneof_type::forward(ref v)) => v,
            _ => Forward::default_instance(),
        }
    }
    pub fn clear_forward(&mut self) {
        self.field_type = ::std::option::Option::None;
    }

    pub fn has_forward(&self) -> bool {
        match self.field_type {
            ::std::option::Option::Some(Msg_oneof_type::forward(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_forward(&mut self, v: Forward) {
        self.field_type = ::std::option::Option::Some(Msg_oneof_type::forward(v))
    }

    // Mutable pointer to the field.
    pub fn mut_forward(&mut self) -> &mut Forward {
        if let ::std::option::Option::Some(Msg_oneof_type::forward(_)) = self.field_type {
        } else {
            self.field_type = ::std::option::Option::Some(Msg_oneof_type::forward(Forward::new()));
        }
        match self.field_type {
            ::std::option::Option::Some(Msg_oneof_type::forward(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_forward(&mut self) -> Forward {
        if self.has_forward() {
            match self.field_type.take() {
                ::std::option::Option::Some(Msg_oneof_type::forward(v)) => v,
                _ => panic!(),
            }
        } else {
            Forward::new()
        }
    }

    // .mirbft.Checkpoint checkpoint = 5;


    pub fn get_checkpoint(&self) -> &Checkpoint {
        match self.field_type {
            ::std::option::Option::Some(Msg_oneof_type::checkpoint(ref v)) => v,
            _ => Checkpoint::default_instance(),
        }
    }
    pub fn clear_checkpoint(&mut self) {
        self.field_type = ::std::option::Option::None;
    }

    pub fn has_checkpoint(&self) -> bool {
        match self.field_type {
            ::std::option::Option::Some(Msg_oneof_type::checkpoint(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_checkpoint(&mut self, v: Checkpoint) {
        self.field_type = ::std::option::Option::Some(Msg_oneof_type::checkpoint(v))
    }

    // Mutable pointer to the field.
    pub fn mut_checkpoint(&mut self) -> &mut Checkpoint {
        if let ::std::option::Option::Some(Msg_oneof_type::checkpoint(_)) = self.field_type {
        } else {
            self.field_type = ::std::option::Option::Some(Msg_oneof_type::checkpoint(Checkpoint::new()));
        }
        match self.field_type {
            ::std::option::Option::Some(Msg_oneof_type::checkpoint(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_checkpoint(&mut self) -> Checkpoint {
        if self.has_checkpoint() {
            match self.field_type.take() {
                ::std::option::Option::Some(Msg_oneof_type::checkpoint(v)) => v,
                _ => panic!(),
            }
        } else {
            Checkpoint::new()
        }
    }
}

impl ::protobuf::Message for Msg {
    fn is_initialized(&self) -> bool {
        if let Some(Msg_oneof_type::preprepare(ref v)) = self.field_type {
            if !v.is_initialized() {
                return false;
            }
        }
        if let Some(Msg_oneof_type::prepare(ref v)) = self.field_type {
            if !v.is_initialized() {
                return false;
            }
        }
        if let Some(Msg_oneof_type::commit(ref v)) = self.field_type {
            if !v.is_initialized() {
                return false;
            }
        }
        if let Some(Msg_oneof_type::forward(ref v)) = self.field_type {
            if !v.is_initialized() {
                return false;
            }
        }
        if let Some(Msg_oneof_type::checkpoint(ref v)) = self.field_type {
            if !v.is_initialized() {
                return false;
            }
        }
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.field_type = ::std::option::Option::Some(Msg_oneof_type::preprepare(is.read_message()?));
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.field_type = ::std::option::Option::Some(Msg_oneof_type::prepare(is.read_message()?));
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.field_type = ::std::option::Option::Some(Msg_oneof_type::commit(is.read_message()?));
                },
                4 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.field_type = ::std::option::Option::Some(Msg_oneof_type::forward(is.read_message()?));
                },
                5 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.field_type = ::std::option::Option::Some(Msg_oneof_type::checkpoint(is.read_message()?));
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let ::std::option::Option::Some(ref v) = self.field_type {
            match v {
                &Msg_oneof_type::preprepare(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                },
                &Msg_oneof_type::prepare(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                },
                &Msg_oneof_type::commit(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                },
                &Msg_oneof_type::forward(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                },
                &Msg_oneof_type::checkpoint(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if let ::std::option::Option::Some(ref v) = self.field_type {
            match v {
                &Msg_oneof_type::preprepare(ref v) => {
                    os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                },
                &Msg_oneof_type::prepare(ref v) => {
                    os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                },
                &Msg_oneof_type::commit(ref v) => {
                    os.write_tag(3, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                },
                &Msg_oneof_type::forward(ref v) => {
                    os.write_tag(4, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                },
                &Msg_oneof_type::checkpoint(ref v) => {
                    os.write_tag(5, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                },
            };
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> Msg {
        Msg::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, Preprepare>(
                    "preprepare",
                    Msg::has_preprepare,
                    Msg::get_preprepare,
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, Prepare>(
                    "prepare",
                    Msg::has_prepare,
                    Msg::get_prepare,
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, Commit>(
                    "commit",
                    Msg::has_commit,
                    Msg::get_commit,
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, Forward>(
                    "forward",
                    Msg::has_forward,
                    Msg::get_forward,
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, Checkpoint>(
                    "checkpoint",
                    Msg::has_checkpoint,
                    Msg::get_checkpoint,
                ));
                ::protobuf::reflect::MessageDescriptor::new::<Msg>(
                    "Msg",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static Msg {
        static mut instance: ::protobuf::lazy::Lazy<Msg> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const Msg,
        };
        unsafe {
            instance.get(Msg::new)
        }
    }
}

impl ::protobuf::Clear for Msg {
    fn clear(&mut self) {
        self.field_type = ::std::option::Option::None;
        self.field_type = ::std::option::Option::None;
        self.field_type = ::std::option::Option::None;
        self.field_type = ::std::option::Option::None;
        self.field_type = ::std::option::Option::None;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for Msg {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Msg {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct Preprepare {
    // message fields
    pub seq_no: u64,
    pub epoch: u64,
    pub bucket: u64,
    pub batch: ::protobuf::RepeatedField<::std::vec::Vec<u8>>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a Preprepare {
    fn default() -> &'a Preprepare {
        <Preprepare as ::protobuf::Message>::default_instance()
    }
}

impl Preprepare {
    pub fn new() -> Preprepare {
        ::std::default::Default::default()
    }

    // uint64 seq_no = 1;


    pub fn get_seq_no(&self) -> u64 {
        self.seq_no
    }
    pub fn clear_seq_no(&mut self) {
        self.seq_no = 0;
    }

    // Param is passed by value, moved
    pub fn set_seq_no(&mut self, v: u64) {
        self.seq_no = v;
    }

    // uint64 epoch = 2;


    pub fn get_epoch(&self) -> u64 {
        self.epoch
    }
    pub fn clear_epoch(&mut self) {
        self.epoch = 0;
    }

    // Param is passed by value, moved
    pub fn set_epoch(&mut self, v: u64) {
        self.epoch = v;
    }

    // uint64 bucket = 3;


    pub fn get_bucket(&self) -> u64 {
        self.bucket
    }
    pub fn clear_bucket(&mut self) {
        self.bucket = 0;
    }

    // Param is passed by value, moved
    pub fn set_bucket(&mut self, v: u64) {
        self.bucket = v;
    }

    // repeated bytes batch = 4;


    pub fn get_batch(&self) -> &[::std::vec::Vec<u8>] {
        &self.batch
    }
    pub fn clear_batch(&mut self) {
        self.batch.clear();
    }

    // Param is passed by value, moved
    pub fn set_batch(&mut self, v: ::protobuf::RepeatedField<::std::vec::Vec<u8>>) {
        self.batch = v;
    }

    // Mutable pointer to the field.
    pub fn mut_batch(&mut self) -> &mut ::protobuf::RepeatedField<::std::vec::Vec<u8>> {
        &mut self.batch
    }

    // Take field
    pub fn take_batch(&mut self) -> ::protobuf::RepeatedField<::std::vec::Vec<u8>> {
        ::std::mem::replace(&mut self.batch, ::protobuf::RepeatedField::new())
    }
}

impl ::protobuf::Message for Preprepare {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.seq_no = tmp;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.epoch = tmp;
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.bucket = tmp;
                },
                4 => {
                    ::protobuf::rt::read_repeated_bytes_into(wire_type, is, &mut self.batch)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.seq_no != 0 {
            my_size += ::protobuf::rt::value_size(1, self.seq_no, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.epoch != 0 {
            my_size += ::protobuf::rt::value_size(2, self.epoch, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.bucket != 0 {
            my_size += ::protobuf::rt::value_size(3, self.bucket, ::protobuf::wire_format::WireTypeVarint);
        }
        for value in &self.batch {
            my_size += ::protobuf::rt::bytes_size(4, &value);
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if self.seq_no != 0 {
            os.write_uint64(1, self.seq_no)?;
        }
        if self.epoch != 0 {
            os.write_uint64(2, self.epoch)?;
        }
        if self.bucket != 0 {
            os.write_uint64(3, self.bucket)?;
        }
        for v in &self.batch {
            os.write_bytes(4, &v)?;
        };
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> Preprepare {
        Preprepare::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "seq_no",
                    |m: &Preprepare| { &m.seq_no },
                    |m: &mut Preprepare| { &mut m.seq_no },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "epoch",
                    |m: &Preprepare| { &m.epoch },
                    |m: &mut Preprepare| { &mut m.epoch },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "bucket",
                    |m: &Preprepare| { &m.bucket },
                    |m: &mut Preprepare| { &mut m.bucket },
                ));
                fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                    "batch",
                    |m: &Preprepare| { &m.batch },
                    |m: &mut Preprepare| { &mut m.batch },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<Preprepare>(
                    "Preprepare",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static Preprepare {
        static mut instance: ::protobuf::lazy::Lazy<Preprepare> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const Preprepare,
        };
        unsafe {
            instance.get(Preprepare::new)
        }
    }
}

impl ::protobuf::Clear for Preprepare {
    fn clear(&mut self) {
        self.seq_no = 0;
        self.epoch = 0;
        self.bucket = 0;
        self.batch.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for Preprepare {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Preprepare {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct Prepare {
    // message fields
    pub seq_no: u64,
    pub epoch: u64,
    pub bucket: u64,
    pub digest: ::std::vec::Vec<u8>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a Prepare {
    fn default() -> &'a Prepare {
        <Prepare as ::protobuf::Message>::default_instance()
    }
}

impl Prepare {
    pub fn new() -> Prepare {
        ::std::default::Default::default()
    }

    // uint64 seq_no = 1;


    pub fn get_seq_no(&self) -> u64 {
        self.seq_no
    }
    pub fn clear_seq_no(&mut self) {
        self.seq_no = 0;
    }

    // Param is passed by value, moved
    pub fn set_seq_no(&mut self, v: u64) {
        self.seq_no = v;
    }

    // uint64 epoch = 2;


    pub fn get_epoch(&self) -> u64 {
        self.epoch
    }
    pub fn clear_epoch(&mut self) {
        self.epoch = 0;
    }

    // Param is passed by value, moved
    pub fn set_epoch(&mut self, v: u64) {
        self.epoch = v;
    }

    // uint64 bucket = 3;


    pub fn get_bucket(&self) -> u64 {
        self.bucket
    }
    pub fn clear_bucket(&mut self) {
        self.bucket = 0;
    }

    // Param is passed by value, moved
    pub fn set_bucket(&mut self, v: u64) {
        self.bucket = v;
    }

    // bytes digest = 4;


    pub fn get_digest(&self) -> &[u8] {
        &self.digest
    }
    pub fn clear_digest(&mut self) {
        self.digest.clear();
    }

    // Param is passed by value, moved
    pub fn set_digest(&mut self, v: ::std::vec::Vec<u8>) {
        self.digest = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_digest(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.digest
    }

    // Take field
    pub fn take_digest(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.digest, ::std::vec::Vec::new())
    }
}

impl ::protobuf::Message for Prepare {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.seq_no = tmp;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.epoch = tmp;
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.bucket = tmp;
                },
                4 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.digest)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.seq_no != 0 {
            my_size += ::protobuf::rt::value_size(1, self.seq_no, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.epoch != 0 {
            my_size += ::protobuf::rt::value_size(2, self.epoch, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.bucket != 0 {
            my_size += ::protobuf::rt::value_size(3, self.bucket, ::protobuf::wire_format::WireTypeVarint);
        }
        if !self.digest.is_empty() {
            my_size += ::protobuf::rt::bytes_size(4, &self.digest);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if self.seq_no != 0 {
            os.write_uint64(1, self.seq_no)?;
        }
        if self.epoch != 0 {
            os.write_uint64(2, self.epoch)?;
        }
        if self.bucket != 0 {
            os.write_uint64(3, self.bucket)?;
        }
        if !self.digest.is_empty() {
            os.write_bytes(4, &self.digest)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> Prepare {
        Prepare::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "seq_no",
                    |m: &Prepare| { &m.seq_no },
                    |m: &mut Prepare| { &mut m.seq_no },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "epoch",
                    |m: &Prepare| { &m.epoch },
                    |m: &mut Prepare| { &mut m.epoch },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "bucket",
                    |m: &Prepare| { &m.bucket },
                    |m: &mut Prepare| { &mut m.bucket },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                    "digest",
                    |m: &Prepare| { &m.digest },
                    |m: &mut Prepare| { &mut m.digest },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<Prepare>(
                    "Prepare",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static Prepare {
        static mut instance: ::protobuf::lazy::Lazy<Prepare> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const Prepare,
        };
        unsafe {
            instance.get(Prepare::new)
        }
    }
}

impl ::protobuf::Clear for Prepare {
    fn clear(&mut self) {
        self.seq_no = 0;
        self.epoch = 0;
        self.bucket = 0;
        self.digest.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for Prepare {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Prepare {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct Commit {
    // message fields
    pub seq_no: u64,
    pub epoch: u64,
    pub bucket: u64,
    pub digest: ::std::vec::Vec<u8>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a Commit {
    fn default() -> &'a Commit {
        <Commit as ::protobuf::Message>::default_instance()
    }
}

impl Commit {
    pub fn new() -> Commit {
        ::std::default::Default::default()
    }

    // uint64 seq_no = 1;


    pub fn get_seq_no(&self) -> u64 {
        self.seq_no
    }
    pub fn clear_seq_no(&mut self) {
        self.seq_no = 0;
    }

    // Param is passed by value, moved
    pub fn set_seq_no(&mut self, v: u64) {
        self.seq_no = v;
    }

    // uint64 epoch = 2;


    pub fn get_epoch(&self) -> u64 {
        self.epoch
    }
    pub fn clear_epoch(&mut self) {
        self.epoch = 0;
    }

    // Param is passed by value, moved
    pub fn set_epoch(&mut self, v: u64) {
        self.epoch = v;
    }

    // uint64 bucket = 3;


    pub fn get_bucket(&self) -> u64 {
        self.bucket
    }
    pub fn clear_bucket(&mut self) {
        self.bucket = 0;
    }

    // Param is passed by value, moved
    pub fn set_bucket(&mut self, v: u64) {
        self.bucket = v;
    }

    // bytes digest = 4;


    pub fn get_digest(&self) -> &[u8] {
        &self.digest
    }
    pub fn clear_digest(&mut self) {
        self.digest.clear();
    }

    // Param is passed by value, moved
    pub fn set_digest(&mut self, v: ::std::vec::Vec<u8>) {
        self.digest = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_digest(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.digest
    }

    // Take field
    pub fn take_digest(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.digest, ::std::vec::Vec::new())
    }
}

impl ::protobuf::Message for Commit {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.seq_no = tmp;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.epoch = tmp;
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.bucket = tmp;
                },
                4 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.digest)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.seq_no != 0 {
            my_size += ::protobuf::rt::value_size(1, self.seq_no, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.epoch != 0 {
            my_size += ::protobuf::rt::value_size(2, self.epoch, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.bucket != 0 {
            my_size += ::protobuf::rt::value_size(3, self.bucket, ::protobuf::wire_format::WireTypeVarint);
        }
        if !self.digest.is_empty() {
            my_size += ::protobuf::rt::bytes_size(4, &self.digest);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if self.seq_no != 0 {
            os.write_uint64(1, self.seq_no)?;
        }
        if self.epoch != 0 {
            os.write_uint64(2, self.epoch)?;
        }
        if self.bucket != 0 {
            os.write_uint64(3, self.bucket)?;
        }
        if !self.digest.is_empty() {
            os.write_bytes(4, &self.digest)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> Commit {
        Commit::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "seq_no",
                    |m: &Commit| { &m.seq_no },
                    |m: &mut Commit| { &mut m.seq_no },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "epoch",
                    |m: &Commit| { &m.epoch },
                    |m: &mut Commit| { &mut m.epoch },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "bucket",
                    |m: &Commit| { &m.bucket },
                    |m: &mut Commit| { &mut m.bucket },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                    "digest",
                    |m: &Commit| { &m.digest },
                    |m: &mut Commit| { &mut m.digest },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<Commit>(
                    "Commit",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static Commit {
        static mut instance: ::protobuf::lazy::Lazy<Commit> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const Commit,
        };
        unsafe {
            instance.get(Commit::new)
        }
    }
}

impl ::protobuf::Clear for Commit {
    fn clear(&mut self) {
        self.seq_no = 0;
        self.epoch = 0;
        self.bucket = 0;
        self.digest.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for Commit {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Commit {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct Checkpoint {
    // message fields
    pub seq_no: u64,
    pub value: ::std::vec::Vec<u8>,
    pub attestation: ::std::vec::Vec<u8>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a Checkpoint {
    fn default() -> &'a Checkpoint {
        <Checkpoint as ::protobuf::Message>::default_instance()
    }
}

impl Checkpoint {
    pub fn new() -> Checkpoint {
        ::std::default::Default::default()
    }

    // uint64 seq_no = 1;


    pub fn get_seq_no(&self) -> u64 {
        self.seq_no
    }
    pub fn clear_seq_no(&mut self) {
        self.seq_no = 0;
    }

    // Param is passed by value, moved
    pub fn set_seq_no(&mut self, v: u64) {
        self.seq_no = v;
    }

    // bytes value = 2;


    pub fn get_value(&self) -> &[u8] {
        &self.value
    }
    pub fn clear_value(&mut self) {
        self.value.clear();
    }

    // Param is passed by value, moved
    pub fn set_value(&mut self, v: ::std::vec::Vec<u8>) {
        self.value = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_value(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.value
    }

    // Take field
    pub fn take_value(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.value, ::std::vec::Vec::new())
    }

    // bytes attestation = 3;


    pub fn get_attestation(&self) -> &[u8] {
        &self.attestation
    }
    pub fn clear_attestation(&mut self) {
        self.attestation.clear();
    }

    // Param is passed by value, moved
    pub fn set_attestation(&mut self, v: ::std::vec::Vec<u8>) {
        self.attestation = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_attestation(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.attestation
    }

    // Take field
    pub fn take_attestation(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.attestation, ::std::vec::Vec::new())
    }
}

impl ::protobuf::Message for Checkpoint {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.seq_no = tmp;
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.value)?;
                },
                3 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.attestation)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.seq_no != 0 {
            my_size += ::protobuf::rt::value_size(1, self.seq_no, ::protobuf::wire_format::WireTypeVarint);
        }
        if !self.value.is_empty() {
            my_size += ::protobuf::rt::bytes_size(2, &self.value);
        }
        if !self.attestation.is_empty() {
            my_size += ::protobuf::rt::bytes_size(3, &self.attestation);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if self.seq_no != 0 {
            os.write_uint64(1, self.seq_no)?;
        }
        if !self.value.is_empty() {
            os.write_bytes(2, &self.value)?;
        }
        if !self.attestation.is_empty() {
            os.write_bytes(3, &self.attestation)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> Checkpoint {
        Checkpoint::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "seq_no",
                    |m: &Checkpoint| { &m.seq_no },
                    |m: &mut Checkpoint| { &mut m.seq_no },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                    "value",
                    |m: &Checkpoint| { &m.value },
                    |m: &mut Checkpoint| { &mut m.value },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                    "attestation",
                    |m: &Checkpoint| { &m.attestation },
                    |m: &mut Checkpoint| { &mut m.attestation },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<Checkpoint>(
                    "Checkpoint",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static Checkpoint {
        static mut instance: ::protobuf::lazy::Lazy<Checkpoint> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const Checkpoint,
        };
        unsafe {
            instance.get(Checkpoint::new)
        }
    }
}

impl ::protobuf::Clear for Checkpoint {
    fn clear(&mut self) {
        self.seq_no = 0;
        self.value.clear();
        self.attestation.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for Checkpoint {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Checkpoint {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct Forward {
    // message fields
    pub epoch: u64,
    pub bucket: u64,
    pub data: ::std::vec::Vec<u8>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a Forward {
    fn default() -> &'a Forward {
        <Forward as ::protobuf::Message>::default_instance()
    }
}

impl Forward {
    pub fn new() -> Forward {
        ::std::default::Default::default()
    }

    // uint64 epoch = 1;


    pub fn get_epoch(&self) -> u64 {
        self.epoch
    }
    pub fn clear_epoch(&mut self) {
        self.epoch = 0;
    }

    // Param is passed by value, moved
    pub fn set_epoch(&mut self, v: u64) {
        self.epoch = v;
    }

    // uint64 bucket = 2;


    pub fn get_bucket(&self) -> u64 {
        self.bucket
    }
    pub fn clear_bucket(&mut self) {
        self.bucket = 0;
    }

    // Param is passed by value, moved
    pub fn set_bucket(&mut self, v: u64) {
        self.bucket = v;
    }

    // bytes data = 3;


    pub fn get_data(&self) -> &[u8] {
        &self.data
    }
    pub fn clear_data(&mut self) {
        self.data.clear();
    }

    // Param is passed by value, moved
    pub fn set_data(&mut self, v: ::std::vec::Vec<u8>) {
        self.data = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_data(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.data
    }

    // Take field
    pub fn take_data(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.data, ::std::vec::Vec::new())
    }
}

impl ::protobuf::Message for Forward {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.epoch = tmp;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.bucket = tmp;
                },
                3 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.data)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.epoch != 0 {
            my_size += ::protobuf::rt::value_size(1, self.epoch, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.bucket != 0 {
            my_size += ::protobuf::rt::value_size(2, self.bucket, ::protobuf::wire_format::WireTypeVarint);
        }
        if !self.data.is_empty() {
            my_size += ::protobuf::rt::bytes_size(3, &self.data);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if self.epoch != 0 {
            os.write_uint64(1, self.epoch)?;
        }
        if self.bucket != 0 {
            os.write_uint64(2, self.bucket)?;
        }
        if !self.data.is_empty() {
            os.write_bytes(3, &self.data)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> Forward {
        Forward::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "epoch",
                    |m: &Forward| { &m.epoch },
                    |m: &mut Forward| { &mut m.epoch },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "bucket",
                    |m: &Forward| { &m.bucket },
                    |m: &mut Forward| { &mut m.bucket },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                    "data",
                    |m: &Forward| { &m.data },
                    |m: &mut Forward| { &mut m.data },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<Forward>(
                    "Forward",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static Forward {
        static mut instance: ::protobuf::lazy::Lazy<Forward> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const Forward,
        };
        unsafe {
            instance.get(Forward::new)
        }
    }
}

impl ::protobuf::Clear for Forward {
    fn clear(&mut self) {
        self.epoch = 0;
        self.bucket = 0;
        self.data.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for Forward {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Forward {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x0cmirbft.proto\x12\x06mirbft\"\xfd\x01\n\x03Msg\x124\n\npreprepare\
    \x18\x01\x20\x01(\x0b2\x12.mirbft.PreprepareH\0R\npreprepare\x12+\n\x07p\
    repare\x18\x02\x20\x01(\x0b2\x0f.mirbft.PrepareH\0R\x07prepare\x12(\n\
    \x06commit\x18\x03\x20\x01(\x0b2\x0e.mirbft.CommitH\0R\x06commit\x12+\n\
    \x07forward\x18\x04\x20\x01(\x0b2\x0f.mirbft.ForwardH\0R\x07forward\x124\
    \n\ncheckpoint\x18\x05\x20\x01(\x0b2\x12.mirbft.CheckpointH\0R\ncheckpoi\
    ntB\x06\n\x04type\"g\n\nPreprepare\x12\x15\n\x06seq_no\x18\x01\x20\x01(\
    \x04R\x05seqNo\x12\x14\n\x05epoch\x18\x02\x20\x01(\x04R\x05epoch\x12\x16\
    \n\x06bucket\x18\x03\x20\x01(\x04R\x06bucket\x12\x14\n\x05batch\x18\x04\
    \x20\x03(\x0cR\x05batch\"f\n\x07Prepare\x12\x15\n\x06seq_no\x18\x01\x20\
    \x01(\x04R\x05seqNo\x12\x14\n\x05epoch\x18\x02\x20\x01(\x04R\x05epoch\
    \x12\x16\n\x06bucket\x18\x03\x20\x01(\x04R\x06bucket\x12\x16\n\x06digest\
    \x18\x04\x20\x01(\x0cR\x06digest\"e\n\x06Commit\x12\x15\n\x06seq_no\x18\
    \x01\x20\x01(\x04R\x05seqNo\x12\x14\n\x05epoch\x18\x02\x20\x01(\x04R\x05\
    epoch\x12\x16\n\x06bucket\x18\x03\x20\x01(\x04R\x06bucket\x12\x16\n\x06d\
    igest\x18\x04\x20\x01(\x0cR\x06digest\"[\n\nCheckpoint\x12\x15\n\x06seq_\
    no\x18\x01\x20\x01(\x04R\x05seqNo\x12\x14\n\x05value\x18\x02\x20\x01(\
    \x0cR\x05value\x12\x20\n\x0battestation\x18\x03\x20\x01(\x0cR\x0battesta\
    tion\"K\n\x07Forward\x12\x14\n\x05epoch\x18\x01\x20\x01(\x04R\x05epoch\
    \x12\x16\n\x06bucket\x18\x02\x20\x01(\x04R\x06bucket\x12\x12\n\x04data\
    \x18\x03\x20\x01(\x0cR\x04dataJ\x97\x0e\n\x06\x12\x04\x06\03\x01\nY\n\
    \x01\x0c\x12\x03\x06\0\x122O\nCopyright\x20IBM\x20Corp.\x20All\x20Rights\
    \x20Reserved.\n\nSPDX-License-Identifier:\x20Apache-2.0\n\n\x08\n\x01\
    \x02\x12\x03\x08\0\x0f\n\n\n\x02\x04\0\x12\x04\n\0\x12\x01\n\n\n\x03\x04\
    \0\x01\x12\x03\n\x08\x0b\n\x0c\n\x04\x04\0\x08\0\x12\x04\x0b\x04\x11\x05\
    \n\x0c\n\x05\x04\0\x08\0\x01\x12\x03\x0b\n\x0e\n\x0b\n\x04\x04\0\x02\0\
    \x12\x03\x0c\x08\"\n\x0c\n\x05\x04\0\x02\0\x06\x12\x03\x0c\x08\x12\n\x0c\
    \n\x05\x04\0\x02\0\x01\x12\x03\x0c\x13\x1d\n\x0c\n\x05\x04\0\x02\0\x03\
    \x12\x03\x0c\x20!\n\x0b\n\x04\x04\0\x02\x01\x12\x03\r\x08\x1c\n\x0c\n\
    \x05\x04\0\x02\x01\x06\x12\x03\r\x08\x0f\n\x0c\n\x05\x04\0\x02\x01\x01\
    \x12\x03\r\x10\x17\n\x0c\n\x05\x04\0\x02\x01\x03\x12\x03\r\x1a\x1b\n\x0b\
    \n\x04\x04\0\x02\x02\x12\x03\x0e\x08\x1a\n\x0c\n\x05\x04\0\x02\x02\x06\
    \x12\x03\x0e\x08\x0e\n\x0c\n\x05\x04\0\x02\x02\x01\x12\x03\x0e\x0f\x15\n\
    \x0c\n\x05\x04\0\x02\x02\x03\x12\x03\x0e\x18\x19\n\x0b\n\x04\x04\0\x02\
    \x03\x12\x03\x0f\x08\x1c\n\x0c\n\x05\x04\0\x02\x03\x06\x12\x03\x0f\x08\
    \x0f\n\x0c\n\x05\x04\0\x02\x03\x01\x12\x03\x0f\x10\x17\n\x0c\n\x05\x04\0\
    \x02\x03\x03\x12\x03\x0f\x1a\x1b\n\x0b\n\x04\x04\0\x02\x04\x12\x03\x10\
    \x08\"\n\x0c\n\x05\x04\0\x02\x04\x06\x12\x03\x10\x08\x12\n\x0c\n\x05\x04\
    \0\x02\x04\x01\x12\x03\x10\x13\x1d\n\x0c\n\x05\x04\0\x02\x04\x03\x12\x03\
    \x10\x20!\n\n\n\x02\x04\x01\x12\x04\x14\0\x19\x01\n\n\n\x03\x04\x01\x01\
    \x12\x03\x14\x08\x12\n\x0b\n\x04\x04\x01\x02\0\x12\x03\x15\x04\x16\n\r\n\
    \x05\x04\x01\x02\0\x04\x12\x04\x15\x04\x14\x14\n\x0c\n\x05\x04\x01\x02\0\
    \x05\x12\x03\x15\x04\n\n\x0c\n\x05\x04\x01\x02\0\x01\x12\x03\x15\x0b\x11\
    \n\x0c\n\x05\x04\x01\x02\0\x03\x12\x03\x15\x14\x15\n\x0b\n\x04\x04\x01\
    \x02\x01\x12\x03\x16\x04\x15\n\r\n\x05\x04\x01\x02\x01\x04\x12\x04\x16\
    \x04\x15\x16\n\x0c\n\x05\x04\x01\x02\x01\x05\x12\x03\x16\x04\n\n\x0c\n\
    \x05\x04\x01\x02\x01\x01\x12\x03\x16\x0b\x10\n\x0c\n\x05\x04\x01\x02\x01\
    \x03\x12\x03\x16\x13\x14\n\x0b\n\x04\x04\x01\x02\x02\x12\x03\x17\x04\x16\
    \n\r\n\x05\x04\x01\x02\x02\x04\x12\x04\x17\x04\x16\x15\n\x0c\n\x05\x04\
    \x01\x02\x02\x05\x12\x03\x17\x04\n\n\x0c\n\x05\x04\x01\x02\x02\x01\x12\
    \x03\x17\x0b\x11\n\x0c\n\x05\x04\x01\x02\x02\x03\x12\x03\x17\x14\x15\n\
    \x0b\n\x04\x04\x01\x02\x03\x12\x03\x18\x04\x1d\n\x0c\n\x05\x04\x01\x02\
    \x03\x04\x12\x03\x18\x04\x0c\n\x0c\n\x05\x04\x01\x02\x03\x05\x12\x03\x18\
    \r\x12\n\x0c\n\x05\x04\x01\x02\x03\x01\x12\x03\x18\x13\x18\n\x0c\n\x05\
    \x04\x01\x02\x03\x03\x12\x03\x18\x1b\x1c\n\n\n\x02\x04\x02\x12\x04\x1b\0\
    \x20\x01\n\n\n\x03\x04\x02\x01\x12\x03\x1b\x08\x0f\n\x0b\n\x04\x04\x02\
    \x02\0\x12\x03\x1c\x04\x16\n\r\n\x05\x04\x02\x02\0\x04\x12\x04\x1c\x04\
    \x1b\x11\n\x0c\n\x05\x04\x02\x02\0\x05\x12\x03\x1c\x04\n\n\x0c\n\x05\x04\
    \x02\x02\0\x01\x12\x03\x1c\x0b\x11\n\x0c\n\x05\x04\x02\x02\0\x03\x12\x03\
    \x1c\x14\x15\n\x0b\n\x04\x04\x02\x02\x01\x12\x03\x1d\x04\x15\n\r\n\x05\
    \x04\x02\x02\x01\x04\x12\x04\x1d\x04\x1c\x16\n\x0c\n\x05\x04\x02\x02\x01\
    \x05\x12\x03\x1d\x04\n\n\x0c\n\x05\x04\x02\x02\x01\x01\x12\x03\x1d\x0b\
    \x10\n\x0c\n\x05\x04\x02\x02\x01\x03\x12\x03\x1d\x13\x14\n\x0b\n\x04\x04\
    \x02\x02\x02\x12\x03\x1e\x04\x16\n\r\n\x05\x04\x02\x02\x02\x04\x12\x04\
    \x1e\x04\x1d\x15\n\x0c\n\x05\x04\x02\x02\x02\x05\x12\x03\x1e\x04\n\n\x0c\
    \n\x05\x04\x02\x02\x02\x01\x12\x03\x1e\x0b\x11\n\x0c\n\x05\x04\x02\x02\
    \x02\x03\x12\x03\x1e\x14\x15\n\x0b\n\x04\x04\x02\x02\x03\x12\x03\x1f\x04\
    \x15\n\r\n\x05\x04\x02\x02\x03\x04\x12\x04\x1f\x04\x1e\x16\n\x0c\n\x05\
    \x04\x02\x02\x03\x05\x12\x03\x1f\x04\t\n\x0c\n\x05\x04\x02\x02\x03\x01\
    \x12\x03\x1f\n\x10\n\x0c\n\x05\x04\x02\x02\x03\x03\x12\x03\x1f\x13\x14\n\
    \n\n\x02\x04\x03\x12\x04\"\0'\x01\n\n\n\x03\x04\x03\x01\x12\x03\"\x08\
    \x0e\n\x0b\n\x04\x04\x03\x02\0\x12\x03#\x04\x16\n\r\n\x05\x04\x03\x02\0\
    \x04\x12\x04#\x04\"\x10\n\x0c\n\x05\x04\x03\x02\0\x05\x12\x03#\x04\n\n\
    \x0c\n\x05\x04\x03\x02\0\x01\x12\x03#\x0b\x11\n\x0c\n\x05\x04\x03\x02\0\
    \x03\x12\x03#\x14\x15\n\x0b\n\x04\x04\x03\x02\x01\x12\x03$\x04\x15\n\r\n\
    \x05\x04\x03\x02\x01\x04\x12\x04$\x04#\x16\n\x0c\n\x05\x04\x03\x02\x01\
    \x05\x12\x03$\x04\n\n\x0c\n\x05\x04\x03\x02\x01\x01\x12\x03$\x0b\x10\n\
    \x0c\n\x05\x04\x03\x02\x01\x03\x12\x03$\x13\x14\n\x0b\n\x04\x04\x03\x02\
    \x02\x12\x03%\x04\x16\n\r\n\x05\x04\x03\x02\x02\x04\x12\x04%\x04$\x15\n\
    \x0c\n\x05\x04\x03\x02\x02\x05\x12\x03%\x04\n\n\x0c\n\x05\x04\x03\x02\
    \x02\x01\x12\x03%\x0b\x11\n\x0c\n\x05\x04\x03\x02\x02\x03\x12\x03%\x14\
    \x15\n\x0b\n\x04\x04\x03\x02\x03\x12\x03&\x04\x15\n\r\n\x05\x04\x03\x02\
    \x03\x04\x12\x04&\x04%\x16\n\x0c\n\x05\x04\x03\x02\x03\x05\x12\x03&\x04\
    \t\n\x0c\n\x05\x04\x03\x02\x03\x01\x12\x03&\n\x10\n\x0c\n\x05\x04\x03\
    \x02\x03\x03\x12\x03&\x13\x14\n\n\n\x02\x04\x04\x12\x04)\0-\x01\n\n\n\
    \x03\x04\x04\x01\x12\x03)\x08\x12\n\x0b\n\x04\x04\x04\x02\0\x12\x03*\x04\
    \x16\n\r\n\x05\x04\x04\x02\0\x04\x12\x04*\x04)\x14\n\x0c\n\x05\x04\x04\
    \x02\0\x05\x12\x03*\x04\n\n\x0c\n\x05\x04\x04\x02\0\x01\x12\x03*\x0b\x11\
    \n\x0c\n\x05\x04\x04\x02\0\x03\x12\x03*\x14\x15\n\x0b\n\x04\x04\x04\x02\
    \x01\x12\x03+\x04\x14\n\r\n\x05\x04\x04\x02\x01\x04\x12\x04+\x04*\x16\n\
    \x0c\n\x05\x04\x04\x02\x01\x05\x12\x03+\x04\t\n\x0c\n\x05\x04\x04\x02\
    \x01\x01\x12\x03+\n\x0f\n\x0c\n\x05\x04\x04\x02\x01\x03\x12\x03+\x12\x13\
    \n\x0b\n\x04\x04\x04\x02\x02\x12\x03,\x04\x1a\n\r\n\x05\x04\x04\x02\x02\
    \x04\x12\x04,\x04+\x14\n\x0c\n\x05\x04\x04\x02\x02\x05\x12\x03,\x04\t\n\
    \x0c\n\x05\x04\x04\x02\x02\x01\x12\x03,\n\x15\n\x0c\n\x05\x04\x04\x02\
    \x02\x03\x12\x03,\x18\x19\n\n\n\x02\x04\x05\x12\x04/\03\x01\n\n\n\x03\
    \x04\x05\x01\x12\x03/\x08\x0f\n\x0b\n\x04\x04\x05\x02\0\x12\x030\x04\x15\
    \n\r\n\x05\x04\x05\x02\0\x04\x12\x040\x04/\x11\n\x0c\n\x05\x04\x05\x02\0\
    \x05\x12\x030\x04\n\n\x0c\n\x05\x04\x05\x02\0\x01\x12\x030\x0b\x10\n\x0c\
    \n\x05\x04\x05\x02\0\x03\x12\x030\x13\x14\n\x0b\n\x04\x04\x05\x02\x01\
    \x12\x031\x04\x16\n\r\n\x05\x04\x05\x02\x01\x04\x12\x041\x040\x15\n\x0c\
    \n\x05\x04\x05\x02\x01\x05\x12\x031\x04\n\n\x0c\n\x05\x04\x05\x02\x01\
    \x01\x12\x031\x0b\x11\n\x0c\n\x05\x04\x05\x02\x01\x03\x12\x031\x14\x15\n\
    \x0b\n\x04\x04\x05\x02\x02\x12\x032\x04\x13\n\r\n\x05\x04\x05\x02\x02\
    \x04\x12\x042\x041\x16\n\x0c\n\x05\x04\x05\x02\x02\x05\x12\x032\x04\t\n\
    \x0c\n\x05\x04\x05\x02\x02\x01\x12\x032\n\x0e\n\x0c\n\x05\x04\x05\x02\
    \x02\x03\x12\x032\x11\x12b\x06proto3\
";

static mut file_descriptor_proto_lazy: ::protobuf::lazy::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::lazy::Lazy {
    lock: ::protobuf::lazy::ONCE_INIT,
    ptr: 0 as *const ::protobuf::descriptor::FileDescriptorProto,
};

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    unsafe {
        file_descriptor_proto_lazy.get(|| {
            parse_descriptor_proto()
        })
    }
}
